language: java
notifications:
  irc:
    channels:
      - "irc.freenode.org#jnr"
    on_success: change
    on_failure: always
    template:
      - "%{repository} (%{branch}:%{commit} by %{author}): %{message} (%{build_url})"
matrix:
  include:
    - os: os x
    - os: linux
      jdk: oraclejdk8
    - os: linux
      jdk: oraclejdk7
    - os: linux
      jdk: openjdk6
    - sudo: required
      services:
       - docker
      before_install:
       - docker pull ibmcom/ibmjava:8-sdk
      script:
        - docker run -v `pwd`:/work ibmcom/ibmjava:8-sdk /bin/sh -c "cd work; ./mvnw clean test"
sudo: false
cache:
  directories:
  - $HOME/.m2
